# Generated by Django 3.0.6 on 2020-05-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('join_date', models.DateField()),
                ('end_date', models.DateField()),
                ('position', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
